[ids]
*

[main]

# Tap for menu, hold for super
meta = overload(meta, f13)

# Maps CapsLock to 'overload(control, esc)'
# Hold = Control
# Tap = Escape
capslock = overload(control, esc)

# Optional: Remaps the physical Left Control to be CapsLock
# (Useful if you ever actually need CapsLock functionality)
leftcontrol = capslock

