#!/usr/bin/env bash

STATE_FILE="$HOME/.config/waybar/Bar_Visible"

# Remove STATE_FILE if it exists
[ -f "$STATE_FILE" ] && rm "$STATE_FILE"

# Kill Waybar & AutoHide Script
pkill -9 -x waybar

# Wait a moment
sleep 0.2

# Relaunch
nohup waybar >/dev/null 2>&1 &
