#!/usr/bin/env bash
set -o pipefail
shopt -s extglob

export SUDO_PROMPT=$'\e[1;38;2;0;255;64m  > ENTER PASSPHRASE: \e[0m'

install_arch_updates() {
    printf "\e[1;38;2;0;255;64m┏━  ┏┓┓┏┏┓┏┳┓┏┓┳┳┓  ┳┳┏┓┳┓┏┓┏┳┓┏┓  ━┓
┃   ┗┓┗┫┗┓ ┃ ┣ ┃┃┃  ┃┃┃┃┃┃┣┫ ┃ ┣    ┃
┗━  ┗┛┗┛┗┛ ┻ ┗┛┛ ┗  ┗┛┣┛┻┛┛┗ ┻ ┗┛  ━┛\e[0m\n"

    sudo -p "$SUDO_PROMPT" pacman -Syu

    printf "\e[38;2;0;255;64m┏━  ┳┳┏┓┏┓┳┓  ┳┓┏┓┏┓┏┓┏┓┳┏┳┓┏┓┳┓┳┏┓┏┓  ━┓
┃   ┃┃┗┓┣ ┣┫  ┣┫┣ ┃┃┃┃┗┓┃ ┃ ┃┃┣┫┃┣ ┗┓   ┃
┗━  ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┗┛┗┛┻ ┻ ┗┛┛┗┻┗┛┗┛  ━┛\e[0m\n"

    if command -v yay &> /dev/null; then
        yay -Syu
    fi

    if command -v flatpak &> /dev/null; then
        printf "\e[38;2;0;255;64m┏━  ┏┓┓ ┏┓┏┳┓┏┓┏┓┓┏┓  ┏┓┏┓┏┓┏┳┓┓ ┏┏┓┳┓┏┓  ━┓
┃   ┣ ┃ ┣┫ ┃ ┃┃┣┫┃┫   ┗┓┃┃┣  ┃ ┃┃┃┣┫┣┫┣    ┃
┗━  ┻ ┗┛┛┗ ┻ ┣┛┛┗┛┗┛  ┗┛┗┛┻  ┻ ┗┻┛┛┗┛┗┗┛  ━┛\e[0m\n"
        flatpak update -y
    fi

    printf "\e[38;2;0;255;64m┏━  ┳┳┏┓┳┓┏┓┏┳┓┏┓┏┓  ┏┓┏┓┳┳┓┏┓┓ ┏┓┏┳┓┏┓╻  ━┓
┃   ┃┃┃┃┃┃┣┫ ┃ ┣ ┗┓  ┃ ┃┃┃┃┃┃┃┃ ┣  ┃ ┣ ┃   ┃
┗━  ┗┛┣┛┻┛┛┗ ┻ ┗┛┗┛  ┗┛┗┛┛ ┗┣┛┗┛┗┛ ┻ ┗┛•  ━┛\e[0m\n"
}

list_updates() {
    ICON=""
    MAX=20
    LINE_MAX=40
    BLACKLIST_FILE="$HOME/.config/waybar/Modules/BlacklistUpdates"

    while pid=$(pgrep -x checkupdates); do
        wait "$pid" 2>/dev/null || true
    done
    sleep 1

    BLACKLIST_PATTERNS=()
    if [[ -f "$BLACKLIST_FILE" ]]; then
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            [[ "$line" =~ ^# ]] && continue
            BLACKLIST_PATTERNS+=("$line")
        done < "$BLACKLIST_FILE"
    fi

    is_blacklisted() {
        local pkg="$1"
        for pattern in "${BLACKLIST_PATTERNS[@]}"; do
            [[ "$pkg" == $pattern ]] && return 0
        done
        return 1
    }

limit_versions() {
    awk '
    function limit_ver(v,   i,cnt,result) {
        result=""
        cnt=0
        for(i=1;i<=length(v);i++){
            c=substr(v,i,1)
            if(c ~ /[^0-9]/){
                cnt++
                if(cnt>2){ result=result"+"; break }
            }
            result=result c
        }
        return result
    }
    {
        pkg=$1
        old=$2
        arrow=$3
        new=$4
        print pkg, limit_ver(old), "", limit_ver(new)
    }'
}

    official_full=$(checkupdates 2>/dev/null)
    aur_full=$(yay -Qum 2>/dev/null)

    official_total=$(printf "%s\n" "$official_full" | grep -c .)
    aur_total=$(printf "%s\n" "$aur_full" | grep -c .)

    filter_blacklist() {
        while IFS= read -r line; do
            pkg=$(printf "%s" "$line" | awk '{print $1}')
            if ! is_blacklisted "$pkg"; then
                printf "%s\n" "$line"
            fi
        done
    }

    official_filtered=$(printf "%s\n" "$official_full" | filter_blacklist)
    aur_filtered=$(printf "%s\n" "$aur_full" | filter_blacklist)

    official_shown=$(printf "%s\n" "$official_filtered" | head -n "$MAX" | grep -c .)
    aur_shown=$(printf "%s\n" "$aur_filtered" | grep -c .)

    official_hidden=$((official_total - official_shown))
    aur_hidden=$((aur_total - aur_shown))

    official=$(printf "%s\n" "$official_filtered" | head -n "$MAX" | limit_versions | awk -v max="$LINE_MAX" '{if(length($0)>max){print substr($0,1,max-3)"...";} else {print}}')
    aur=$(printf "%s\n" "$aur_filtered" | limit_versions)

    center_text() {
        awk -v width="$LINE_MAX" '{len=length($0); if(len>=width){print; next}; pad_left=int((width-len)/2); pad_right=width-len-pad_left; printf "%*s%s%*s\n", pad_left,"",$0,pad_right,""}'
    }

    official_header=$(printf " [ OFFICIAL REPOSITORIES ]" | center_text)
    aur_header=$(printf " [ USER REPOSITORIES ]" | center_text)

    if (( official_hidden > 0 )); then
        official+=$'\n'"$(printf " +%s MORE " "$official_hidden" | center_text)"
    fi
    if (( aur_hidden > 0 )); then
        aur+=$'\n'"$(printf " +%s MORE " "$aur_hidden" | center_text)"
    fi

    tooltip=""
    [[ -n "$official_filtered" ]] && tooltip="$official_header"$'\n'"$official"
    [[ -n "$official_filtered" && -n "$aur_filtered" ]] && tooltip+=$'\n\n'
    [[ -n "$aur_filtered" ]] && tooltip+="$aur_header"$'\n'"$aur"

    total_updates=$((official_total + aur_total))
    updates_upper=$(printf "%s" "$total_updates" | tr '[:lower:]' '[:upper:]')
    tooltip_upper=$(printf "%s" "$tooltip" | awk '{print toupper($0)}')

    if [[ "$updates_upper" == "0" ]]; then
        jq -nc --arg text "" --arg tooltip "$tooltip_upper" '{text: $text, tooltip: $tooltip}'
    else
        jq -nc --arg text "[ "$ICON" "$updates_upper" ]" --arg tooltip "$tooltip_upper" '{text: $text, tooltip: $tooltip}'
    fi
}

case "$1" in
    module) list_updates ;;
    *)
        install_arch_updates
        printf "\e[1;38;2;0;255;153m         [ PRESS ANY KEY TO EXIT ]\e[0m\n"
        read -n 1
        ;;
esac
