# -- General Settings --
# Increase scroll history
set -g history-limit 10000
# Start window and pane numbering from 1
set -g base-index 1
set-window-option -g pane-base-index 1
set -g pane-base-index 1
# Remove delay when pressing Escape (useful for Vim/Neovim)
set -s escape-time 0
# Switch windows using Alt + Number (No prefix needed due to -n flag)
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9 
# Cycle windows (No prefix needed)
bind-key -n M-h previous-window
bind-key -n M-l next-window
# Allow automatic renaming of windows based on running process
set-window-option -g automatic-rename on
# Set terminal to support True Color (24-bit)
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# -- Mouse Interaction --
# Enable full mouse support (scroll, window/pane selection)
set -g mouse on

# -- Keybinds --
# Prevent tmux from exiting copy-mode when releasing mouse
unbind -T copy-mode-vi MouseDragEnd1Pane
# To copy to system clipboard on release, without clearing selection, you need a "pipe"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "wl-copy"

# Change prefix key from C-b to C-a (more ergonomic)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload tmux configuration with 'prefix + r'
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded!"

# Navigate between panes with Alt + Arrows (without prefix)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# -- Appearance (Status Bar) --
# Status bar colors
set -g status-style bg=black,fg=white
# Active window color
set-window-option -g window-status-current-style fg=white,bold
# Remove the right side of the status bar
set -g status-right ""
# Status bar position
set -g status-position top
# Center the window list
set -g status-justify centre