# -- Configurações Gerais --
# Aumenta o histórico de scroll
set -g history-limit 10000
# Inicia a numeração de janelas e painéis a partir de 1
set -g base-index 1
set-window-option -g pane-base-index 1
set -g pane-base-index 1
# Remove o delay ao pressionar a tecla Escape (útil para Vim/Neovim)
set -s escape-time 0
# Switch windows using Alt + Number (No prefix needed due to -n flag)
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9 
# Cycle windows (No prefix needed)
bind-key -n M-h previous-window
bind-key -n M-l next-window
# Permite renomear janelas automaticamente com base no processo em execução
set-window-option -g automatic-rename on
# Define o terminal para suportar True Color (24-bit)
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# -- Interação com o Mouse --
# Ativa o suporte completo ao mouse (scroll, seleção de janelas/painéis)
set -g mouse on

# -- Atalhos (Keybinds) --
# Evita que o tmux saia do copy-mode ao soltar o mouse
unbind -T copy-mode-vi MouseDragEnd1Pane
# Para copiar para o clipboard do sistema ao soltar, sem limpar a seleção, você precisa de um "pipe"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "wl-copy"

# Altera a tecla de prefixo de C-b para C-a (mais ergonômico)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Recarrega a configuração do tmux com 'prefixo + r'
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded!"

# Navegação entre painéis com Alt + Setas (sem precisar do prefixo)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# -- Aparência (Status Bar) --
# Cores da barra de status
set -g status-style bg=black,fg=white
# Cor da janela Ativa 
set-window-option -g window-status-current-style fg=white,bold
# Remove o lado direito da barra de status
set -g status-right ""
# Posição da barra
set -g status-position top
# Centraliza a lista de janelas
set -g status-justify centre
