# Splash text rendering
splash = false
# Disabling IPC prevents from using hyprctl hyprpaper to change wallpapers dynamically on the fly
ipc = off

wallpaper {
  monitor = HDMI-A-1
  path = $HOME/.config/hypr/wallpapers/a_street_with_signs_and_lights.png
  fit_mode = cover
}

