-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

-- monitor=,preferred,auto,auto

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "dolphin"

local menu = "rofi -show drun -modi drun,calc"

local codeWorkspace = "kitty"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:














--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__NV_PRIME_RENDER_OFFLOAD", 1)

hl.env("__VK_LAYER_NV_optimus", "NVIDIA_only")

hl.env("MOZ_DISABLE_SOCKET_PROCESS", 1)

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

hl.config({
    ecosystem = {
        no_donation_nag = true,
    },
})

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 1,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgba(91d7e3ee)",
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule {

--     name = no-gaps-wtv1

--     match:float = false

--     match:workspace = w[tv1]

--

--     border_size = 0

--     rounding = 0

-- }

--

-- windowrule {

--     name = no-gaps-f1

--     match:float = false

--     match:workspace = f[1]

--

--     border_size = 0

--     rounding = 0

-- }

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "br",
        kb_variant = "abnt2",
        -- 0 = cursor movement will not change focus (disables "hover the mouse to select window")
        follow_mouse = 0,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Rofi Launcher

hl.bind("Pause", hl.dsp.exec_cmd("pkill rofi || rofi -show drun -modi drun,calc"))

-- Screenshot: Full Screen (Clipboard)

hl.bind("Print", hl.dsp.exec_cmd("grim-| wl-copy"))

-- Screenshot: Select Region (Clipboard)

hl.bind("SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| wl-copy"))

-- Screenshot: Select Region -> Edit (Swappy)

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| swappy -f-"))

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "u", hl.dsp.exec_cmd("/home/runner/dotfiles/hypr/.config/hypr/scripts/summon_code-workspace.sh 1 kitty"))

hl.bind(mainMod .. " + " .. "i", hl.dsp.exec_cmd("/home/runner/dotfiles/hypr/.config/hypr/scripts/summon_vivaldi.sh"))

hl.bind(mainMod .. " + " .. "o", hl.dsp.exec_cmd("/home/runner/dotfiles/hypr/.config/hypr/scripts/summon_betterbird.sh"))

hl.bind(mainMod .. " + " .. "p", hl.dsp.exec_cmd("/home/runner/dotfiles/hypr/.config/hypr/scripts/summon_obsidian.sh"))

hl.bind(mainMod .. " + " .. "q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "escape", hl.dsp.exec_cmd("systemctl suspend"))

hl.bind(mainMod .. " + " .. "m", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))

hl.bind(mainMod .. " + " .. "e", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "f", hl.dsp.window.fullscreen())

--bind = $mainMod, V, togglefloating,

hl.bind(mainMod .. " + " .. "v", hl.dsp.exec_cmd("voxtype record start"))

hl.bind(mainMod .. " + " .. "v", hl.dsp.exec_cmd("voxtype record stop"), { repeating = true })

--bind = $mainMod, R, exec, $menu

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "p", hl.dsp.window.pseudo())

-- dwindle

-- Rebound togglesplit from J to backslash so J can be used for vim motions

hl.bind(mainMod .. " + " .. "backslash", hl.dsp.layout("togglesplit"))

-- dwindle

-- Move focus with mainMod CTRL + arrow keys and vim motions

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = "5" }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = "6" }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = "7" }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = "8" }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = "9" }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = "10" }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = "11" }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = "12" }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = "13" }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = "14" }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "u", hl.dsp.window.move({ workspace = "1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "i", hl.dsp.window.move({ workspace = "2" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "o", hl.dsp.window.move({ workspace = "3" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "p", hl.dsp.window.move({ workspace = "4" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = "5" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = "6" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = "7" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = "8" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = "9" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = "10" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = "11" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = "12" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = "13" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = "14" }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "s", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "s", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Navigate between workspaces (like Cosmic DE)

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ workspace = "m+1" }))

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ workspace = "m-1" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ workspace = "m-1" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ workspace = "m+1" }))

-- Vim motions for window navigation

hl.bind(mainMod .. " + " .. "l", hl.dsp.window.cycle_next())

hl.bind(mainMod .. " + " .. "h", hl.dsp.window.cycle_next({ next = false }))

hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ workspace = "m-1" }))

hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ workspace = "m+1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

--bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+

--bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

--bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

--bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

--bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+

--bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

-- Volume Control via pamixer

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t"))

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Group Navigation and Management

hl.bind(mainMod .. " + " .. "g", hl.dsp.group.toggle())

-- Toggle window group (stack)

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.group.next())

-- Cycle to next window in stack                              │

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.group.next({ forward = false }))

-- Cycle to prev window 

-- Moving windows into/out of the stack

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "h", hl.dsp.window.move({ into_group = "left" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "l", hl.dsp.window.move({ into_group = "right" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "k", hl.dsp.window.move({ into_group = "up" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "j", hl.dsp.window.move({ into_group = "down" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "g", hl.dsp.window.move({ out_of_group = true }))

-- Eject window from stack

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

hl.config({
    group = {
        -- visual settings
        groupbar = {
            enabled = true,
            font_family = "JetBrainsMono Nerd Font",
            font_size = 10,
            text_color = "0xffffffff",
            ["col.active"] = "rgba(ca9ee6ff)",
            ["col.inactive"] = "rgba(b4befecc)",
        },
        col = {
            border_active = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            border_inactive = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
            border_locked_active = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            border_locked_inactive = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
        },
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("sleep 2 && kanshi")
    hl.exec_cmd("dunst")
    hl.exec_cmd("sleep 2 && hyprpaper")
    hl.exec_cmd("nm-applet &")
    hl.exec_cmd("waybar &")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("[workspace 1 silent] kitty tmux")
    hl.exec_cmd("[workspace 2 silent] vivaldi --ozone-platform=wayland --enable-features=UseOzonePlatform --use-gl=desktop --use-cmd-decoder=validating")
    hl.exec_cmd("[workspace 3 silent] bash -c \"sleep 2 && /home/runner/.config/hypr/scripts/betterbird.sh\"")
    hl.exec_cmd("[workspace 4 silent] " .. os.getenv("HOME") .. "/.local/bin/Obsidian-1.11.5.AppImage")
    hl.exec_cmd("voxtype")
    hl.exec_cmd("/usr/lib/pam_kwallet_init")
end)
