# Splash text rendering
splash = false
# Disabling IPC prevents from using hyprctl hyprpaper to change wallpapers dynamically on the fly
ipc = off

# Load the image into RAM
preload = $HOME/.config/hypr/wallpapers/archlinux-logo-center.png

# Apply the preloaded image to the monitor
wallpaper = HDMI-A-1, $HOME/.config/hypr/wallpapers/archlinux-logo-center.png
