--return {
--  "zbirenbaum/copilot.lua",
--  cmd = "Copilot",
--  event = "InsertEnter",
--  config = function()
--    require("copilot").setup({
--      suggestion = {
--        enabled = true,
--        auto_trigger = true,
--        keymap = {
--          accept = "<C-y>", -- Explicitly map Control+Y to accept AI
--          next = "<M-]>",
--          prev = "<M-[>",
--          dismiss = "<C-]>",
--        },
--      },
--      panel = { enabled = false },
--      filetypes = { markdown = true, help = true },
--    })
--  end,
--}
