#include ~/.config/kitty/theme.conf

# Default background_opacity is 0.70
background_opacity 0.90

cursor_trail 0
enable_audio_bell no

italic_font auto
bold_font auto
font_family JetBrainsMono Nerd Font 
font_size 20.0
bold_italic_font auto

# This section is for window
# padding for window width, recommend 5
window_padding_width 5
# this is padding for windows, witdh, recommend 5
window_margin_width 5
# This disable the confirmation of close window, the value is 0
confirm_os_window_close 0
hide_window_decorations yes

# Smart Copy/Paste Configuration

# 1. COPY (Smart)
# If text is selected, copy to clipboard.
# If NO selection, send SIGINT (Interrupt) signal to terminal.
map ctrl+c copy_or_interrupt

# 2. PASTE
# Force paste from system clipboard, ignoring shell's "Verbatim Insert".
map ctrl+v paste_from_clipboard

# Escape Route: Ctrl+Shift+V sends original signal
# \x16 is the ASCII hexadecimal code for Control-V (Synchronous Idle)
map ctrl+shift+v send_text all \x16

